# fly.toml app configuration file generated for satsbook-api on 2026-05-17T13:10:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'satsbook-api'
primary_region = 'iad'

[build]
  dockerfile = 'deploy/licenseserver/Dockerfile'

[env]
  SATSBOOK_LICENSE_DB_PATH = '/data/licenses.db'

[mounts]
  source = 'licensedb'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
